name: Feature request
description: Suggest an idea
title: "[feat] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem are you trying to solve? Whose problem, in what context?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: How might Disk Cleaner solve it? Sketches / screenshots welcome.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
